class Lagerblatt
  include DataMapper::Resource
  include DataMapper::Validate

  # Properties
  property :id,               Serial
  property  :lagernr,  String   #  alt Lagblatt LAGERNR
  property  :blatt,  String   #  alt Lagblatt BLATT
  property  :eingang,  String   #  alt Lagblatt EINGANG
  property  :ausgang,  String   #  alt Lagblatt AUSGANG
  property  :kunde,  String   #  alt Lagblatt KUNDE
  property  :anzahl,  String   #  alt Lagblatt ANZAHL
  property  :aufbeschrieb,  String   #  alt Lagblatt AUFBESCHRIEB
  property  :mueller,  String   #  alt Lagblatt Müller
  property  :ansatz,  String   #  alt Lagblatt ANSATZ
  property  :total_arbeit,  String   #  alt Lagblatt Total_Arbeit
  property  :inventarwert,  String   #  alt Lagblatt Inventarwert
  property  :zuschlag1,  String   #  alt Lagblatt Zuschlag1
  property  :ztotal,  String   #  alt Lagblatt Ztotal
  property  :zuschlag_,  String   #  alt Lagblatt Zuschlag_
  property  :administrat,  String   #  alt Lagblatt Administrat
  property  :kalkpreis,  String   #  alt Lagblatt Kalkpreis
  property  :grundpreis,  String   #  alt Lagblatt Grundpreis
  property  :vertriebfaktor,  String   #  alt Lagblatt VertriebFaktor
  property  :versfrgerechnet,  String   #  alt Lagblatt VerSFRgerechnet
  property  :versfrgerundet,  String   #  alt Lagblatt VerSFRgerundet
  property  :ge_gp_,  String   #  alt Lagblatt GE_GP_
  property  :gegerechnet,  String   #  alt Lagblatt GEgerechnet
  property  :gegerundet,  String   #  alt Lagblatt GEgerundet
  property  :sachetnr,  String   #  alt Lagblatt Sachetnr
  property  :auftragnr,  String   #  alt Lagblatt Auftragnr
  property  :pos,  String   #  alt Lagblatt Pos
  property  :grundpreis_stk,  String   #  alt Lagblatt Grundpreis_STK
  property  :hinweis,  String   #  alt Lagblatt Hinweis
  property  :versfrpreis,  String   #  alt Lagblatt VerSFRPreis
  property  :vkge,  String   #  alt Lagblatt VKGE
  property  :zuschlag_2,  String   #  alt Lagblatt ZUSCHLAG_2
  property  :zuschlag_groesse,  String   #  alt Lagblatt ZUSCHLAGGrösse
  property  :kostenvoransch,  String   #  alt Lagblatt Kostenvoransch
  property  :sachetbeschrieb,  String   #  alt Lagblatt Sachetbeschrieb
  property  :gewichttot,  String   #  alt Lagblatt Gewichttot
  property  :gewichtstk,  String   #  alt Lagblatt GewichtStk
  property  :goldtot,  String   #  alt Lagblatt Goldtot
  property  :goldstk,  String   #  alt Lagblatt GoldStk
  property  :platintot,  String   #  alt Lagblatt Platintot
  property  :platinstk,  String   #  alt Lagblatt PlatinStk
  property  :silbertot,  String   #  alt Lagblatt Silbertot
  property  :silberstk,  String   #  alt Lagblatt Silberstk
  property  :bezandere,  String   #  alt Lagblatt Bezandere
  property  :bezanderetot,  String   #  alt Lagblatt Bezanderetot
  property  :bezanderestk,  String   #  alt Lagblatt Bezanderestk
  property  :prozzuschl,  String   #  alt Lagblatt PROZZUSCHL
  property  :adminstk,  String   #  alt Lagblatt AdminStk
  property  :bezugs_groesse,  String   #  alt Lagblatt Bezgrösse
  property  :groesse_stueck,  String   #  alt Lagblatt GrösseStk
  property  :textzu1,  String   #  alt Lagblatt TEXTZU1
  property  :textzu2,  String   #  alt Lagblatt TEXTZU2
  property  :archiv,  String   #  alt Lagblatt ARCHIV
  property  :vorrat,  String   #  alt Lagblatt Vorrat
  property  :invent_x_vorat,  String   #  alt Lagblatt INVENT_X_VORAT
  property  :aufgeloest,  String   #  alt Lagblatt AUFGELÖST
  property  :effektivpreis,  String   #  alt Lagblatt EFFEKTIVPREIS
  property  :preisstufe,  String   #  alt Lagblatt PREISSTUFE
  property  :preisliste,  String   #  alt Lagblatt PREISLISTE
  property  :vorratdatum,  String   #  alt Lagblatt VORRATDATUM
  property  :mueller_x_ansatz,  String   #  alt Lagblatt MüllerXANSATZ
  property  :kundenum,  String   #  alt Lagblatt KUNDENUM
  property  :gold_total_aktuell,  String   #  alt Lagblatt Goldtot aktuell
  property  :pt_total_aktuell,  String   #  alt Lagblatt Pt tot aktuell
  property  :ag_total_aktuell,  String   #  alt Lagblatt Ag tot aktuell
  property  :andere_aktuell,  String   #  alt Lagblatt andere aktuell
  property  :selektion,  String   #  alt Lagblatt Selektion
  property  :berechengrundla,  String   #  alt Lagblatt Berechengrundla
  property  :lag_blatt_index,  String   #  alt Lagblatt LAG_BLATT_INDEX
  property  :lagbild,  String   #  alt Lagblatt LAGBILD
  property  :selektion2,  String   #  alt Lagblatt Selektion2
  property  :selektion2menge,  String   #  alt Lagblatt Selektion2Menge
  property  :wer03,  String   #  alt Lagblatt WER03
  property  :wer04,  String   #  alt Lagblatt WER04
  property  :anzahl_std03,  String   #  alt Lagblatt ANZAHL_STD03
  property  :anzahl_std04,  String   #  alt Lagblatt ANZAHL_STD04
  property  :ansatz_std_04,  String   #  alt Lagblatt ANSATZ_STD_04
  property  :ansatz_std_03,  String   #  alt Lagblatt ANSATZ_STD_03
  property  :stunden_pro_stueck,  String   #  alt Lagblatt STD_PRO_STÜCK
  property  :inventarwert_st,  String   #  alt Lagblatt INVENTARWERT_ST
  property  :totalarbeit_st,  String   #  alt Lagblatt TOTALARBEIT_ST
  property  :gussmodell,  String   #  alt Lagblatt GUSSMODELL
  property  :kollektionsname,  String   #  alt Lagblatt KOLLEKTIONSNAME
  property  :selek_wien,  String   #  alt Lagblatt selek_Wien
  property  :herstellxvorrat,  String   #  alt Lagblatt HerstellXVorrat
  property  :kurzlagtext,  String   #  alt Lagblatt Kurzlagtext
  property  :stundentotal,  String   #  alt Lagblatt Stundentotal
  property  :faktorkatalog,  String   #  alt Lagblatt FaktorKatalog
  property  :kataloggrechnet,  String   #  alt Lagblatt Kataloggrechnet
  property  :katalogerundet,  String   #  alt Lagblatt Katalogerundet
  property  :katalogpreissfr,  String   #  alt Lagblatt KatalogpreisSFR
  property  :set1,  String   #  alt Lagblatt Set1
  property  :merkmal1,  String   #  alt Lagblatt Merkmal1
  property  :merkmal2,  String   #  alt Lagblatt Merkmal2
  property  :herstelproanzah,  String   #  alt Lagblatt HerstelproAnzah
  property  :detbrdfaktor,  String   #  alt Lagblatt DetBRDFaktor
  property  :sfrzueuro,  String   #  alt Lagblatt SFRzuEURO
  property  :detbrdgerundet,  String   #  alt Lagblatt DetBRDgerundet
  property  :detbrdeuropreis,  String   #  alt Lagblatt DetBRDEuroPreis
  property  :vereurogerundet,  String   #  alt Lagblatt VerEUROgerundet
  property  :vereuropreis,  String   #  alt Lagblatt VerEUROPreis
  property  :freipreisfaktor,  String   #  alt Lagblatt FreiPreisFaktor
  property  :freipreisgerund,  String   #  alt Lagblatt FreiPreisgerund
  property  :freivkpreis,  String   #  alt Lagblatt FreiVKPreis
  property  :freipreiswem,  String   #  alt Lagblatt FreiPreisWem
  property  :vkge_schluessel,  String   #  alt Lagblatt VKGEschlüssel
  property  :mateinzelkost1,  String   #  alt Lagblatt mateinzelkost1
  property  :auf_ls,  String   #  alt Lagblatt auf_LS
  property  :auf_lswo,  String   #  alt Lagblatt auf_LSwo
  property  :sumherst,  String   #  alt Lagblatt SumHerst
  property  :katalwem,  String   #  alt Lagblatt KatalWem
  property  :priveurfaktor,  String   #  alt Lagblatt PrivEurFaktor
  property  :priveurgerech,  String   #  alt Lagblatt PrivEurGerech
  property  :priveurgerundet,  String   #  alt Lagblatt PrivEurGerundet
  property  :priveurpreis,  String   #  alt Lagblatt PrivEurPreis
  property  :det_eur_schluessel,  String   #  alt Lagblatt DetEurSchlüssel
  property  :kalkschema,  String   #  alt Lagblatt Kalkschema
  property  :totarbeit_vvgk,  String   #  alt Lagblatt TotArbeit_VVGK
  property  :totarbeit_gezu,  String   #  alt Lagblatt TotArbeit_GEZU
  property  :herstellpreis,  String   #  alt Lagblatt Herstellpreis
  property  :selbstkpreis,  String   #  alt Lagblatt Selbstkpreis
  property  :kalkkostpreis,  String   #  alt Lagblatt Kalkkostpreis
  property  :totmatemgk,  String   #  alt Lagblatt TotMatEMGK
  property  :totmatmak,  String   #  alt Lagblatt TotMatMaK
  property  :totmatvvgk,  String   #  alt Lagblatt TotMatVVGK
  property  :totmatgezu,  String   #  alt Lagblatt TotMatGEZU
  property  :mwst_ansatz,  String   #  alt Lagblatt MWST_Ansatz
  property  :sumlsdet,  String   #  alt Lagblatt SumLsDet
  property  :schmuckart,  String   #  alt Lagblatt Schmuckart
  property  :seitenzahl,  String   #  alt Lagblatt Seitenzahl
  property  :artikelnummer,  String   #  alt Lagblatt Artikelnummer
  property  :albumpreispriv,  String   #  alt Lagblatt AlbumpreisPriv
  property  :albumpreisdet,  String   #  alt Lagblatt AlbumpreisDet
  property  :de_vertrek2_eur,  String   #  alt Lagblatt DE_VertrEK2_EUR
  property  :de_det_ek2_eur,  String   #  alt Lagblatt DE_Det_EK2_EUR
  property  :de_detek_eurkey,  String   #  alt Lagblatt DE_DetEK_EURKey
  property  :de_det_vk2_eur,  String   #  alt Lagblatt DE_Det_VK2_EUR
  property  :ch_vertrek2_chf,  String   #  alt Lagblatt CH_VertrEK2_CHF
  property  :ch_det_ek2,  String   #  alt Lagblatt CH_Det_EK2
  property  :ch_det_ek_key,  String   #  alt Lagblatt CH_Det_EK_Key
  property  :ch_det_vk2,  String   #  alt Lagblatt CH_Det_VK2
  property  :ch_my_endpreis2,  String   #  alt Lagblatt CH_my_Endpreis2
  property  :preis_wann_neu,  String   #  alt Lagblatt Preis_wann_neu
end